"""Canonical capacity profile for the standalone expanded MPT verifier."""

MAX_PROOF_NODES = 16
MAX_NODE_RLP_BYTES = 1024
MAX_TOTAL_PROOF_RLP_BYTES = 8192
MAX_EXTENSION_NODES = 8
MAX_TERMINAL_VALUE_BYTES = 256
ACCOUNT_KEY_BYTES = 32
ACCOUNT_PATH_NIBBLES = 64
MAX_COMPACT_PATH_BYTES = 33
BRANCH_CHILD_SLOTS = 16
WITNESS_VERSION = 1

CAPACITY_NAMES = (
    "MAX_PROOF_NODES",
    "MAX_NODE_RLP_BYTES",
    "MAX_TOTAL_PROOF_RLP_BYTES",
    "MAX_EXTENSION_NODES",
    "MAX_TERMINAL_VALUE_BYTES",
    "ACCOUNT_KEY_BYTES",
    "ACCOUNT_PATH_NIBBLES",
    "MAX_COMPACT_PATH_BYTES",
    "BRANCH_CHILD_SLOTS",
    "WITNESS_VERSION",
)
