#!/usr/bin/env python3
"""Generate and validate standalone K/P Noir capacity modules."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from thesis_c.proof_inputs import expanded_mpt_capacity as capacity


HEADER = "// Generated by scripts/generate_expanded_mpt_capacity.py.\n// Edit thesis_c/proof_inputs/expanded_mpt_capacity.py instead.\n"


def render() -> str:
    lines = [HEADER]
    for name in capacity.CAPACITY_NAMES:
        lines.append(f"global {name}: u32 = {getattr(capacity, name)};\n")
        fn_name = name.lower()
        lines.append(f"pub fn {fn_name}() -> u32 {{ {name} }}\n")
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    paths = [
        ROOT / "circuits_mpt_inclusion/src/expanded_mpt_capacity.nr",
        ROOT / "circuits_mpt_inclusion_poseidon2/src/expanded_mpt_capacity.nr",
    ]
    stale = []
    for path in paths:
        current = path.read_text() if path.exists() else None
        if current != rendered:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(rendered)
    if stale and args.check:
        for path in stale:
            print(f"stale generated capacity file: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
